### ISSUE TITLE
Rule: Event Hubs not properly locked down

### ISSUE THREAD

**Issue by noelbundick** [noelbundick/config-analyzer#18]
With most Azure services, when you enable the firewall - it disables all access except for the rules that you define

For Event Hubs, the service works differently - the default behavior is to allow all connections until you add the first rule. Specifically, this can happen when enabling a private endpoint, and then turning on the firewall - thinking that you're blocking public access - when actually you're not

We should identify these resources as potential misconfiguration issues

**Comment by Joshua-Phelps** [comment]
closed by #81
